import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function CashierPaymentPage() {
  const navigate = useNavigate()
  const [paymentMethod, setPaymentMethod] = useState<'cash' | 'promptpay' | 'card'>('cash')
  return <div className="w-full max-w-[1000px] bg-[#FDFBF7] pb-20"><header className="flex items-center gap-4 border-b border-[#EAE5DF] py-6"><button onClick={() => navigate(-1)} className="rounded-full p-2 text-[#302221] hover:bg-[#F4EFEA]">←</button><div><h1 className="text-xl font-bold text-[#302221]">เช็คบิล / ชำระเงิน</h1><p className="mt-1 text-sm text-[#7B726B]">หน้าจอสำหรับรายการจาก payment API</p></div></header><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-xl border border-[#EAE5DF] bg-white p-6 shadow-sm"><h2 className="font-bold text-[#302221]">รายการอาหาร</h2><div className="mt-6 rounded-xl border-2 border-dashed border-[#EAE5DF] p-12 text-center"><p className="font-bold text-[#302221]">ยังไม่มีรายการชำระเงิน</p><p className="mt-1 text-sm text-[#7B726B]">เลือกโต๊ะหรือออเดอร์จากระบบก่อนดำเนินการ</p></div></section><aside className="rounded-xl border border-[#EAE5DF] bg-white p-6 shadow-sm"><h2 className="font-bold text-[#302221]">Payment method</h2><div className="mt-5 space-y-3">{(['cash', 'promptpay', 'card'] as const).map((method) => <label key={method} className="flex cursor-pointer items-center gap-3 rounded-lg border border-[#EAE5DF] px-3 py-3 text-sm font-bold"><input type="radio" checked={paymentMethod === method} onChange={() => setPaymentMethod(method)} />{method === 'promptpay' ? 'PromptPay' : method === 'cash' ? 'เงินสด' : 'บัตรเครดิต'}</label>)}</div><button disabled className="mt-6 w-full rounded-lg bg-[#5A403E] py-3 text-sm font-bold text-white opacity-50">ยืนยันการชำระเงิน</button></aside></div></div>
}

