FROM postgres:16-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-16-cron && rm -rf /var/lib/apt/lists/*
CMD ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=rims_test", "-c", "cron.launch_active_jobs=off"]
