import { useState } from 'react';
import { useInventory } from '../../contexts/InventoryContext';
import type { InventoryBatch } from '../../mocks/inventory';

const field = 'mt-2 w-full rounded-xl border-2 border-[#2D1B17] bg-[#FFFDF9] px-3.5 py-3 font-semibold text-[#2D1B17] outline-none transition placeholder:text-[#A99188] focus:-translate-y-0.5 focus:shadow-[3px_3px_0_#B97861]';

export default function AddLotPage() {
  const { receiveBatch } = useInventory(); const [saved, setSaved] = useState(false); const [category, setCategory] = useState<InventoryBatch['category']>('Meat');
  return <div className="max-w-4xl"><header className="relative mb-7 overflow-hidden rounded-[28px] border-2 border-[#2D1B17] bg-[#D9B99A] px-7 py-7 shadow-[8px_8px_0_#2D1B17]"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full border-[20px] border-white/35"/><span className="relative inline-flex rotate-[-2deg] rounded-full border-2 border-[#2D1B17] bg-[#E8D8CA] px-3 py-1 text-[10px] font-black shadow-[2px_2px_0_#2D1B17]">NEW DROP ✦</span><h1 className="relative mt-4 text-4xl font-black tracking-[-.035em]">รับของเข้าคลัง</h1><p className="relative mt-2 text-sm font-bold text-[#73552E]">เปิดล็อตใหม่จากใบส่งของ แล้วส่งต่อเข้าคิว FIFO อัตโนมัติ</p></header>{saved && <div className="mb-5 rotate-[-.5deg] rounded-2xl border-2 border-[#2D1B17] bg-[#E8D8CA] px-5 py-4 text-sm font-black shadow-[4px_4px_0_#2D1B17]">✓ ล็อตใหม่เข้า stock แล้ว — พร้อมลุย!</div>}
    <form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); receiveBatch({ item: String(data.get('item')), category, batch: String(data.get('batch')), qty: `${data.get('qty')} ${data.get('unit')}`, receiveDate: String(data.get('receiveDate')), expireDate: String(data.get('expireDate')) }); setSaved(true); event.currentTarget.reset(); }} className="overflow-hidden rounded-[26px] border-2 border-[#2D1B17] bg-white shadow-[7px_7px_0_#2D1B17]"><div className="flex flex-wrap items-center justify-between gap-3 border-b-2 border-[#2D1B17] bg-[#E7C7B8] px-6 py-5"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#8B5746]">Goods receiving</p><h2 className="mt-1 text-xl font-black">รายละเอียดล็อตวัตถุดิบ</h2></div><div className="flex gap-2"><span className="rounded-full border-2 border-[#2D1B17] bg-white px-3 py-1 text-[10px] font-black">1 · LABEL</span><span className="rounded-full border-2 border-[#2D1B17] bg-[#DBC8B8] px-3 py-1 text-[10px] font-black">2 · STORE</span></div></div>
      <div className="grid gap-5 p-6 sm:grid-cols-2"><Field label="ชื่อวัตถุดิบ"><input name="item" required className={field} placeholder="เช่น หมูสามชั้นสไลด์"/></Field><Field label="หมายเลขล็อต"><input name="batch" required className={field} placeholder="เช่น B-0817"/></Field><Field label="หมวดวัตถุดิบ"><select value={category} onChange={(event) => setCategory(event.target.value as InventoryBatch['category'])} className={field}><option value="Meat">🥩 เนื้อสัตว์</option><option value="Vegetable">🥬 ผัก</option><option value="Others">🥫 วัตถุดิบอื่น</option></select></Field><Field label="พื้นที่จัดเก็บ"><select className={field}><option>❄ Freezer Stock</option><option>◫ Prep Fridge</option></select></Field><div className="grid grid-cols-[1fr_130px] gap-3 sm:col-span-2"><Field label="จำนวน"><input name="qty" required type="number" min="0.1" step="0.1" className={field} placeholder="0"/></Field><Field label="หน่วย"><select name="unit" className={field}><option>kg</option><option>packs</option><option>bottles</option><option>liters</option><option>sets</option></select></Field></div><Field label="วันที่รับเข้า"><input name="receiveDate" required type="date" defaultValue="2026-08-17" className={field}/></Field><Field label="วันหมดอายุ"><input name="expireDate" required type="date" className={field}/></Field></div>
      <footer className="flex flex-col-reverse gap-3 border-t-2 border-[#2D1B17] bg-[#F1E2CF] px-6 py-5 sm:flex-row sm:justify-end"><button type="reset" className="rounded-xl border-2 border-[#2D1B17] bg-white px-5 py-2.5 text-sm font-black hover:bg-[#FFF8EF]">ล้างข้อมูล</button><button className="rounded-xl border-2 border-[#2D1B17] bg-[#2D1B17] px-6 py-2.5 text-sm font-black text-white shadow-[4px_4px_0_#B97861] transition hover:-translate-y-0.5">ยืนยันรับเข้า →</button></footer>
    </form>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-black uppercase tracking-[.06em] text-[#513931]">{label}{children}</label>; }
