import { useMemo, useState, type ReactNode } from 'react';
type Status = 'Critical' | 'Low stock' | 'In stock';
type Item = { name: string; category: string; batch: string; remaining: string; expiry: string; status: Status };
const freezer: Item[] = [{ name: 'ลูกชิ้นปลา', category: 'Seafood · Frozen', batch: 'FZ-0811', remaining: '4.5 kg', expiry: '18 Aug 2026', status: 'Critical' }, { name: 'เนื้อวากิวสไลซ์ A5', category: 'Meat · Premium', batch: 'FZ-0810', remaining: '12.0 kg', expiry: '17 Aug 2026', status: 'Low stock' }, { name: 'กุ้งขาว', category: 'Seafood · Frozen', batch: 'FZ-0809', remaining: '8.2 kg', expiry: '22 Aug 2026', status: 'In stock' }, { name: 'ไอศกรีมกะทิ', category: 'Dessert · Frozen', batch: 'FZ-0807', remaining: '3.6 kg', expiry: '20 Aug 2026', status: 'Low stock' }];
const prep: Item[] = [{ name: 'หมูสไลซ์', category: 'Meat · Chilled', batch: 'PR-0811', remaining: '6.0 kg', expiry: '17 Aug 2026', status: 'Low stock' }, { name: 'ชุดผักรวม', category: 'Vegetable · Chilled', batch: 'PR-0811', remaining: '10 sets', expiry: '18 Aug 2026', status: 'In stock' }, { name: 'น้ำจิ้มสุกี้', category: 'Sauce · Chilled', batch: 'PR-0810', remaining: '8 bottles', expiry: '21 Aug 2026', status: 'In stock' }];
const badge: Record<Status, string> = { Critical: 'bg-[#B97861] text-white', 'Low stock': 'bg-[#D9B99A]', 'In stock': 'bg-[#E8D8CA]' };
const label: Record<Status, string> = { Critical: 'ต้องรีบใช้', 'Low stock': 'เหลือน้อย', 'In stock': 'พร้อมใช้' };

export default function KitchenStockPage({ area }: { area: 'Freezer Stock' | 'Prep Fridge' }) {
  const [query, setQuery] = useState(''); const [attentionOnly, setAttentionOnly] = useState(false); const items = area === 'Freezer Stock' ? freezer : prep; const attention = items.filter((item) => item.status !== 'In stock').length; const normal = items.length - attention; const priority = items.find((item) => item.status === 'Critical') ?? items.find((item) => item.status === 'Low stock') ?? items[0]; const visible = useMemo(() => items.filter((item) => `${item.name} ${item.batch}`.toLowerCase().includes(query.toLowerCase()) && (!attentionOnly || item.status !== 'In stock')), [items, query, attentionOnly]);
  return <div className="w-full max-w-[1240px]">
    <header className="relative mb-7 overflow-hidden rounded-[28px] border-2 border-[#2D1B17] bg-[#DBC8B8] px-7 py-7 shadow-[8px_8px_0_#2D1B17]"><div className="absolute -right-8 -top-14 h-48 w-48 rounded-full border-[24px] border-white/30"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="rotate-[-2deg] rounded-full border-2 border-[#2D1B17] bg-[#F1E2CF] px-3 py-1 text-[10px] font-black shadow-[2px_2px_0_#2D1B17]">ZONE {area === 'Freezer Stock' ? 'A-04' : 'B-02'}</span><span className="text-xs font-black text-[#6F554D]">STOCK MODE ✦</span></div><h1 className="mt-4 text-4xl font-black tracking-[-.035em] text-[#2D1B17]">{area === 'Freezer Stock' ? 'คลังแช่แข็ง' : 'ตู้เตรียมครัว'}</h1><p className="mt-2 text-sm font-semibold text-[#7A6057]">เช็กล็อต · ดูวันหมดอายุ · หยิบแบบ FIFO</p></div><label className="flex w-full max-w-xs items-center gap-2 rounded-xl border-2 border-[#2D1B17] bg-white px-3.5 py-3 text-[#7A665F] shadow-[4px_4px_0_#2D1B17] transition focus-within:-translate-y-0.5"><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาของ หรือ batch..." className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none placeholder:text-[#A99690]"/></label></div></header>
    <section className="mb-7 grid gap-5 md:grid-cols-3"><Stat label="ทั้งหมด" value={items.length} note="รายการในโซนนี้" color="bg-[#F1E2CF]" sign="✦"/><Stat label="ต้องเช็ก" value={attention} note="เสี่ยงหมด / เหลือน้อย" color="bg-[#E7C7B8]" sign="!"/><Stat label="พร้อมหยิบ" value={normal} note="ใช้ได้ตามปกติ" color="bg-[#E8D8CA]" sign="✓"/></section>
    <section className="mb-7 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><article className="flex items-center gap-4 rounded-[22px] border-2 border-[#2D1B17] bg-white p-5 shadow-[5px_5px_0_#2D1B17]"><span className="flex h-12 w-12 shrink-0 rotate-[-5deg] items-center justify-center rounded-2xl border-2 border-[#2D1B17] bg-[#B97861] text-xl font-black text-white shadow-[2px_2px_0_#2D1B17]">1</span><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#8B5746]">Pick me first</p><h2 className="mt-1 text-xl font-black">{priority.name} <span className="font-mono text-xs text-[#987D74]">#{priority.batch}</span></h2><p className="mt-1 text-xs font-semibold text-[#80675F]">เหลือ {priority.remaining} · ใช้ภายใน {priority.expiry}</p></div></article><article className="rotate-[1deg] rounded-[22px] border-2 border-[#2D1B17] bg-[#2D1B17] p-5 text-white shadow-[5px_5px_0_#B97861]"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#D4A996]">Crew note</p><p className="mt-2 text-sm font-bold leading-6">หยิบล็อตเก่าก่อน แล้วอัปเดตยอดหลังจบรอบนะ ✦</p></article></section>
    <section className="overflow-hidden rounded-[26px] border-2 border-[#2D1B17] bg-white shadow-[7px_7px_0_#2D1B17]"><div className="flex flex-col gap-4 border-b-2 border-[#2D1B17] bg-[#FFF8EF] px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black">Stock shelf</h2><span className="rounded-full border-2 border-[#2D1B17] bg-[#DBC8B8] px-2 py-0.5 text-[10px] font-black">{items.length} ITEMS</span></div><p className="mt-1 text-xs font-semibold text-[#8A7067]">อัปเดตล่าสุด วันนี้ 08:30 น.</p></div><div className="flex gap-2"><button onClick={() => setAttentionOnly(!attentionOnly)} className={`rounded-xl border-2 border-[#2D1B17] px-3.5 py-2 text-xs font-black shadow-[3px_3px_0_#2D1B17] transition hover:-translate-y-0.5 ${attentionOnly ? 'bg-[#2D1B17] text-white' : 'bg-[#E7C7B8]'}`}>{attentionOnly ? 'ดูทั้งหมด' : `ต้องเช็ก ${attention}`}</button><button className="rounded-xl border-2 border-[#2D1B17] bg-[#E8D8CA] px-3.5 py-2 text-xs font-black shadow-[3px_3px_0_#2D1B17] transition hover:-translate-y-0.5">↓ Export</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-b-2 border-[#2D1B17] bg-[#2D1B17] text-[10px] font-black uppercase tracking-[.14em] text-white"><tr><th className="px-6 py-4">Ingredient</th><th className="px-4 py-4">Batch</th><th className="px-4 py-4">On hand</th><th className="px-4 py-4">Use by</th><th className="px-6 py-4">Status</th></tr></thead><tbody>{visible.map((item, index) => <tr key={item.batch} className="border-b-2 border-[#2D1B17]/10 transition hover:bg-[#F7EDE2] last:border-0"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl border-2 border-[#2D1B17] text-sm font-black shadow-[2px_2px_0_#2D1B17] ${['bg-[#B97861] text-white','bg-[#DBC8B8]','bg-[#E8D8CA]','bg-[#D9B99A]'][index % 4]}`}>{item.name.charAt(0)}</span><div><p className="text-sm font-black">{item.name}</p><p className="mt-0.5 text-[10px] font-bold text-[#92776E]">{item.category}</p></div></div></td><td className="px-4 py-4 font-mono text-xs font-bold text-[#795F56]">#{item.batch}</td><td className="px-4 py-4 text-sm font-black">{item.remaining}</td><td className="px-4 py-4 text-xs font-bold text-[#6E554D]">{item.expiry}</td><td className="px-6 py-4"><span className={`inline-flex rotate-[-1deg] rounded-full border-2 border-[#2D1B17] px-2.5 py-1 text-[10px] font-black ${badge[item.status]}`}>{label[item.status]}</span></td></tr>)}</tbody></table></div>{visible.length === 0 && <div className="py-14 text-center"><p className="text-lg font-black">หาไม่เจอแฮะ 👀</p><p className="mt-1 text-xs font-semibold text-[#876E65]">ลองใช้ชื่อหรือ batch อื่นดูนะ</p></div>}<footer className="flex justify-between border-t-2 border-[#2D1B17] bg-[#F1E2CF] px-6 py-3 text-[10px] font-black uppercase tracking-[.12em]"><span>Showing {visible.length}/{items.length}</span><span>FIFO sorted ✦</span></footer></section>
  </div>;
}

function Stat({ label, value, note, color, sign }: { label: string; value: number; note: string; color: string; sign: string }) { return <article className={`relative overflow-hidden rounded-[22px] border-2 border-[#2D1B17] p-5 shadow-[5px_5px_0_#2D1B17] transition hover:-translate-y-1 ${color}`}><span className="absolute right-4 top-2 text-4xl font-black opacity-20">{sign}</span><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#775B51]">{label}</p><p className="mt-2 text-4xl font-black">{String(value).padStart(2, '0')}</p><p className="mt-1 text-xs font-bold text-[#765F56]">{note}</p></article>; }
const Svg = ({ children }: { children: ReactNode }) => <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{children}</svg>;
const Search = () => <Svg><circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/></Svg>;
