import { useState, type ReactNode } from 'react';
import { useInventory } from '../../contexts/InventoryContext';

const field = 'mt-2 w-full rounded-xl border-2 border-[#2D1B17] bg-[#FFFDF9] px-3.5 py-3 font-semibold text-[#2D1B17] outline-none transition focus:-translate-y-0.5 focus:shadow-[3px_3px_0_#DBC8B8]';

export default function TransferStocksPage() {
  const [submitted, setSubmitted] = useState(false); const { batches } = useInventory(); const usable = batches.filter((batch) => batch.status !== 'Expired');
  return <div className="max-w-4xl"><header className="relative mb-7 overflow-hidden rounded-[28px] border-2 border-[#2D1B17] bg-[#E8D8CA] px-7 py-7 shadow-[8px_8px_0_#2D1B17]"><div className="absolute -right-8 -top-12 h-40 w-40 rounded-full border-[22px] border-white/45"/><span className="relative inline-flex rotate-[2deg] rounded-full border-2 border-[#2D1B17] bg-[#DBC8B8] px-3 py-1 text-[10px] font-black shadow-[2px_2px_0_#2D1B17]">MOVE IT! ↗</span><h1 className="relative mt-4 text-4xl font-black tracking-[-.035em]">โอนย้ายวัตถุดิบ</h1><p className="relative mt-2 text-sm font-bold text-[#6D5147]">ย้ายของจาก Freezer สู่ Prep พร้อมรักษา batch และลำดับ FIFO</p></header>{submitted && <div className="mb-5 rounded-2xl border-2 border-[#2D1B17] bg-[#E8D8CA] px-5 py-4 text-sm font-black shadow-[4px_4px_0_#2D1B17]">✓ Move complete — สต็อกไปถึง Prep แล้ว!</div>}
    <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="overflow-hidden rounded-[26px] border-2 border-[#2D1B17] bg-white shadow-[7px_7px_0_#2D1B17]"><div className="border-b-2 border-[#2D1B17] bg-[#DBC8B8] px-6 py-5"><div className="flex flex-wrap items-center gap-3"><span className="rounded-xl border-2 border-[#2D1B17] bg-[#2D1B17] px-4 py-2 text-xs font-black text-white">❄ FREEZER</span><span className="text-2xl font-black">→</span><span className="rounded-xl border-2 border-[#2D1B17] bg-[#F1E2CF] px-4 py-2 text-xs font-black shadow-[3px_3px_0_#2D1B17]">◫ PREP FRIDGE</span></div><p className="mt-3 text-xs font-bold text-[#72564D]">ล็อตเดิมจะตามไปด้วย เพื่อให้ trace ย้อนกลับได้ทุกครั้ง</p></div>
      <div className="space-y-5 p-6"><Field label="เลือกลอตต้นทาง"><select className={field}>{usable.map((batch) => <option key={batch.id}>{batch.batch} — {batch.item} — เหลือ {batch.qty}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="จำนวนที่ย้าย"><input type="number" min="0.1" step="0.1" required className={field} placeholder="0"/></Field><Field label="หน่วย"><select className={field}><option>kg</option><option>packs</option><option>bottles</option><option>liters</option><option>sets</option></select></Field></div><Field label="เหตุผลการโอน"><select className={field}><option>เตรียมสำหรับรอบบริการ</option><option>เติมสต็อกตู้เตรียม</option><option>ย้ายเพื่อจัดเรียง FIFO</option><option>อื่น ๆ</option></select></Field><Field label="Crew note"><textarea rows={3} className={field} placeholder="ฝากโน้ตให้กะถัดไปได้เลย..."/></Field></div>
      <footer className="flex flex-col-reverse gap-3 border-t-2 border-[#2D1B17] bg-[#E7C7B8] px-6 py-5 sm:flex-row sm:justify-end"><button type="reset" className="rounded-xl border-2 border-[#2D1B17] bg-white px-5 py-2.5 text-sm font-black">ล้างข้อมูล</button><button className="rounded-xl border-2 border-[#2D1B17] bg-[#2D1B17] px-6 py-2.5 text-sm font-black text-white shadow-[4px_4px_0_#D9B99A] transition hover:-translate-y-0.5">ยืนยันการโอน →</button></footer>
    </form>
  </div>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-black uppercase tracking-[.06em] text-[#513931]">{label}{children}</label>; }
