import { useMemo, useState } from 'react'
import { useInventory } from '../../contexts/InventoryContext'

export default function ExpiredGoodsPage() {
  const { batches, loading, error } = useInventory()
  const [query, setQuery] = useState('')
  const expired = useMemo(() => batches.filter((batch) => batch.status === 'Expired' && `${batch.item} ${batch.batch}`.toLowerCase().includes(query.toLowerCase())), [batches, query])
  const expiringSoon = batches.filter((batch) => batch.status === 'Expiring Soon').length
  const lostValue = expired.reduce((total, batch) => total + batch.unitValue, 0)

  return <div className="admin-page w-full max-w-[1200px]">
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h1 className="text-[26px] font-bold text-[#302221]">Expired Goods Check</h1><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ingredients..." className="admin-control w-full rounded-md border-none bg-[#F4EFEA] px-4 py-2.5 text-sm sm:w-[320px]" /></div>
    {error && <div className="mb-5 rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}
    <div className="mb-8 grid grid-cols-1 gap-5 md:grid-cols-3"><Summary label="Loss Value" value={formatCurrency(lostValue)} note="จากล็อตที่หมดอายุในระบบ" /><Summary label="Items For Disposal" value={String(expired.length)} note="ล็อตที่ต้องตรวจสอบ" /><Summary label="Expiring Soon Alerts" value={String(expiringSoon)} note="ล็อตที่ API แจ้งเตือน" /></div>
    <div className="admin-surface overflow-hidden rounded-lg bg-white"><div className="flex flex-col gap-3 border-b border-[#e8e3dd] bg-[#FDFBF7] px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><h2 className="text-lg font-bold text-[#302221]">Expired / Degraded Ingredients List</h2><div className="flex gap-3"><button className="admin-control rounded-md border px-4 py-2 text-sm font-semibold">Filter</button><button className="admin-primary rounded-md px-4 py-2 text-sm font-semibold text-white">Export Report</button></div></div>{loading ? <div className="p-10 text-center text-sm font-bold text-[#7B726B]">กำลังโหลดข้อมูล…</div> : expired.length === 0 ? <div className="p-12 text-center"><p className="font-bold text-[#302221]">ยังไม่มีล็อตหมดอายุ</p><p className="mt-1 text-sm text-[#7B726B]">รายการจะแสดงเมื่อ inventory API มีข้อมูล</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b bg-[#FDFBF7] text-[10px] font-bold uppercase tracking-widest text-[#999]"><th className="px-6 py-4">Ingredient Name</th><th className="px-6 py-4">Batch No.</th><th className="px-6 py-4">Expiry Date</th><th className="px-6 py-4">Quantity</th><th className="px-6 py-4">Value</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y">{expired.map((item) => <tr key={item.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#F4EFEA] text-[#777]">□</span><div><p className="text-sm font-medium text-[#302221]">{item.item}</p><p className="text-xs text-[#7B726B]">{item.category}</p></div></div></td><td className="px-6 py-4 font-mono text-xs text-[#7B726B]">{item.batch}</td><td className="px-6 py-4 text-sm text-[#555]">{item.expireDate}</td><td className="px-6 py-4 text-sm text-[#555]">{item.qty}</td><td className="px-6 py-4 text-sm font-bold text-[#302221]">{formatCurrency(item.unitValue)}</td><td className="px-6 py-4"><span className="rounded-full bg-[#F4EFEA] px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[#7B726B]">Expired</span></td></tr>)}</tbody></table></div>}<div className="border-t border-[#e8e3dd] bg-[#FDFBF7] px-6 py-4 text-xs font-medium text-[#7B726B]">แสดง {expired.length} รายการจากข้อมูลจริง</div></div>
  </div>
}

function Summary({ label, value, note }: { label: string; value: string; note: string }) { return <div className="admin-stat-card flex items-center justify-between rounded-lg bg-white p-6"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-wider text-[#7B726B]">{label}</p><h2 className="text-3xl font-bold text-[#302221]">{value}</h2><p className="mt-1 text-xs text-[#7B726B]">{note}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#F4EFEA] text-xl text-[#555]">⌁</div></div> }
function formatCurrency(value: number) { return `฿${value.toLocaleString('th-TH', { maximumFractionDigits: 2 })}` }
