sonar.projectKey=sepkao_rims
sonar.organization=sepkao

sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.tsbuildinfo
sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info
