import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import { type UserRole, useAuth } from '../contexts/AuthContext';

type IconName = 'grid' | 'snow' | 'fridge' | 'plus' | 'transfer' | 'table' | 'clock' | 'orders';
type NavItem = { name: string; path: string; icon: IconName };
const navigation: Record<Exclude<UserRole, 'admin'>, NavItem[]> = {
  kitchen: [{ name: 'ภาพรวมคลัง', path: '/kitchen', icon: 'grid' }, { name: 'คลังแช่แข็ง', path: '/kitchen/freezer-stock', icon: 'snow' }, { name: 'ตู้เตรียมครัว', path: '/kitchen/prep-fridge', icon: 'fridge' }, { name: 'รับวัตถุดิบเข้า', path: '/kitchen/lots/new', icon: 'plus' }, { name: 'โอนย้ายสต็อก', path: '/kitchen/transfer-stocks', icon: 'transfer' }],
  server: [{ name: 'Dashboard', path: '/server', icon: 'grid' }, { name: 'Dining Tables', path: '/server/tables', icon: 'table' }, { name: 'Serve Queue', path: '/server/serve-queue', icon: 'clock' }],
  cashier: [{ name: 'Table Management', path: '/cashier', icon: 'table' }, { name: 'Orders', path: '/cashier/orders', icon: 'orders' }],
};
const labels: Record<Exclude<UserRole, 'admin'>, string> = { kitchen: 'Kitchen Crew', server: 'Service Crew', cashier: 'Cashier Crew' };

export default function StaffLayout({ role }: { role: Exclude<UserRole, 'admin'> }) {
  const navigate = useNavigate(); const location = useLocation(); const { logout } = useAuth();
  const current = navigation[role].find((item) => item.path === location.pathname) ?? navigation[role][0];
  return <div className="flex min-h-screen bg-[#FFF8EF] font-sans text-[#2D1B17]">
    <aside className="fixed z-20 flex h-full w-[272px] flex-col overflow-hidden border-r-2 border-[#2D1B17] bg-[#2D1B17] text-white">
      <div className="absolute -right-12 -top-12 h-40 w-40 rounded-full border-[24px] border-[#B97861]/20"/><div className="relative px-6 pb-5 pt-7"><div className="flex items-center gap-3"><span className="flex h-12 w-12 rotate-[-5deg] items-center justify-center rounded-2xl border-2 border-[#2D1B17] bg-[#B97861] text-lg font-black text-[#2D1B17] shadow-[4px_4px_0_#D9B99A]">SS</span><div><h1 className="text-lg font-black leading-tight tracking-[.1em]">SHABU STOCK</h1><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-[#D4A996]">Restaurant ops ✦</p></div></div></div>
      <nav className="relative mt-5 flex-1 px-3"><div className="mb-3 flex items-center justify-between px-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#BCA29A]">My workspace</p><span className="rounded-full bg-[#E8D8CA] px-2 py-0.5 text-[9px] font-black text-[#5A4037]">LIVE</span></div><ul className="space-y-1.5">{navigation[role].map((item) => { const active = location.pathname === item.path; return <li key={item.path}><button onClick={() => navigate(item.path)} className={`group flex w-full items-center gap-3 rounded-xl border-2 px-4 py-3 text-left text-[13px] font-bold transition-all ${active ? 'translate-x-1 border-[#2D1B17] bg-[#E7C7B8] text-[#2D1B17] shadow-[4px_4px_0_#B97861]' : 'border-transparent text-[#EADBD5] hover:border-white/10 hover:bg-white/10 hover:text-white'}`}><span className={active ? 'text-[#8B5746]' : 'text-[#C9B1A9]'}><NavIcon name={item.icon}/></span>{item.name}{active && <span className="ml-auto text-sm">↗</span>}</button></li>; })}</ul></nav>
      <div className="relative m-3 rounded-2xl border border-white/10 bg-white/[.06] p-3"><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E8D8CA] text-xs font-black text-[#5A4037]">KC</span><div><p className="text-xs font-bold">{labels[role]}</p><p className="text-[10px] text-[#BCA29A]">Ready for shift ✦</p></div></div><button onClick={() => { logout(); navigate('/', { replace: true }); }} className="w-full rounded-lg bg-white/10 px-3 py-2 text-left text-[11px] font-bold text-[#EADBD5] hover:bg-white/15">Log out →</button></div>
    </aside>
    <main className="ml-[272px] flex min-h-screen flex-1 flex-col bg-[#FFF8EF]" style={{ backgroundImage: 'radial-gradient(circle at 88% 4%, rgba(185,120,97,.13), transparent 22%), radial-gradient(circle at 15% 95%, rgba(232,216,202,.3), transparent 24%)' }}>
      <header className="sticky top-0 z-10 flex h-[72px] items-center justify-between border-b-2 border-[#2D1B17]/10 bg-[#FFF8EF]/85 px-8 backdrop-blur-xl"><div className="flex items-center gap-2 text-sm"><span className="rounded-full bg-[#2D1B17] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-white">{labels[role]}</span><span className="text-[#B4998F]">/</span><span className="font-black text-[#2D1B17]">{current.name}</span></div><div className="flex items-center gap-2"><span className="hidden rounded-full border-2 border-[#2D1B17] bg-[#D9B99A] px-3 py-1 text-[10px] font-black text-[#2D1B17] shadow-[2px_2px_0_#2D1B17] sm:block">SHIFT ACTIVE</span><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-[#2D1B17] bg-[#B97861] text-xs font-black text-[#2D1B17]">KS</span></div></header>
      <div className="flex-1 p-8"><Outlet/></div>
    </main>
  </div>;
}

function NavIcon({ name }: { name: IconName }) { const path = { grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>, snow: <><path d="M12 2v20M4.2 6.5l15.6 11M19.8 6.5l-15.6 11"/></>, fridge: <><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M5 9h14M8 5v1M8 12v2"/></>, plus: <path d="M12 5v14M5 12h14"/>, transfer: <><path d="M4 7h15m0 0-4-4m4 4-4 4M20 17H5m0 0 4 4m-4-4 4-4"/></>, table: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 11h18M9 5v14"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, orders: <path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/> }[name]; return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">{path}</svg>; }
