import { useNavigate } from 'react-router-dom';
import { useInventory } from '../../contexts/InventoryContext';

export default function StaffDashboardPage() {
  const { batches, fifoQueue } = useInventory(); const navigate = useNavigate();
  const usable = batches.filter((batch) => batch.status !== 'Expired'); const expiring = batches.filter((batch) => batch.status === 'Expiring Soon'); const expired = batches.filter((batch) => batch.status === 'Expired');
  const categoryCount = (['Meat', 'Vegetable', 'Others'] as const).map((category) => ({ category, count: usable.filter((batch) => batch.category === category).length }));
  return <div className="w-full max-w-[1240px]">
    <section className="relative mb-7 overflow-hidden rounded-[28px] border-2 border-[#2D1B17] bg-[#B97861] px-7 py-8 shadow-[8px_8px_0_#2D1B17] sm:px-9"><div className="absolute -right-12 -top-16 h-52 w-52 rounded-full border-[28px] border-[#D9B99A]/50"/><div className="absolute bottom-4 right-28 rotate-6 rounded-full border-2 border-[#2D1B17] bg-[#E8D8CA] px-4 py-2 text-xs font-black shadow-[3px_3px_0_#2D1B17]">FIFO FIRST! ✦</div><div className="relative max-w-2xl"><span className="inline-flex rotate-[-2deg] rounded-full border-2 border-[#2D1B17] bg-[#FFF8EF] px-3 py-1 text-[10px] font-black uppercase tracking-[.16em] shadow-[2px_2px_0_#2D1B17]">Restaurant inventory</span><h1 className="mt-5 text-4xl font-black leading-tight tracking-[-.035em] text-[#2D1B17] sm:text-5xl">คลังพร้อม ครัวพร้อม<br/><span className="text-[#FFF8EF] drop-shadow-[2px_2px_0_#2D1B17]">ทุกกะก็พร้อมลุย.</span></h1><p className="mt-4 max-w-lg text-sm font-semibold leading-6 text-[#563128]">เช็กล็อตคงเหลือ จัด FIFO และเคลียร์วัตถุดิบเสี่ยงก่อนเริ่มรอบแบบไม่หลุด flow</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => navigate('/staff/receive-lot')} className="rounded-xl border-2 border-[#2D1B17] bg-[#2D1B17] px-5 py-3 text-sm font-black text-white shadow-[4px_4px_0_#D9B99A] transition hover:-translate-y-0.5">+ รับของเข้าคลัง</button><button onClick={() => navigate('/staff/transfer-to-thaw-prep')} className="rounded-xl border-2 border-[#2D1B17] bg-[#FFF8EF] px-5 py-3 text-sm font-black text-[#2D1B17] shadow-[4px_4px_0_#2D1B17] transition hover:-translate-y-0.5">โอนย้ายสต็อก →</button></div></div></section>

    <section className="mb-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><PopMetric label="พร้อมใช้" value={usable.length} detail="ล็อตที่เบิกใช้ได้" color="bg-[#F1E2CF]" symbol="✦"/><PopMetric label="คิว FIFO" value={fifoQueue.length} detail="รอหยิบตามลำดับ" color="bg-[#DBC8B8]" symbol="↳"/><PopMetric label="ใกล้หมดอายุ" value={expiring.length} detail="ใช้ภายใน 3 วัน" color="bg-[#E7C7B8]" symbol="!"/><PopMetric label="แยกออก" value={expired.length} detail="ห้ามนำไปใช้" color="bg-[#E8D8CA]" symbol="×"/></section>

    <section className="grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><div className="overflow-hidden rounded-[24px] border-2 border-[#2D1B17] bg-white shadow-[6px_6px_0_#2D1B17]"><div className="flex items-center justify-between border-b-2 border-[#2D1B17] bg-[#F1E2CF] px-6 py-5"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7A5544]">Pick list</p><h2 className="mt-1 text-xl font-black text-[#2D1B17]">คิวหยิบแบบ FIFO</h2></div><span className="rotate-2 rounded-full border-2 border-[#2D1B17] bg-white px-3 py-1 text-xs font-black shadow-[2px_2px_0_#2D1B17]">{fifoQueue.length} LOTS</span></div><div className="divide-y-2 divide-[#2D1B17]/10">{fifoQueue.slice(0, 5).map((batch, index) => <div key={batch.id} className="group flex flex-col gap-3 px-6 py-4 transition hover:bg-[#F7EDE2] sm:flex-row sm:items-center"><span className={`flex h-10 w-10 shrink-0 rotate-[-4deg] items-center justify-center rounded-xl border-2 border-[#2D1B17] text-sm font-black shadow-[2px_2px_0_#2D1B17] ${index === 0 ? 'bg-[#B97861]' : 'bg-[#FFF8EF]'}`}>{String(index + 1).padStart(2, '0')}</span><div className="min-w-0 flex-1"><p className="font-black text-[#2D1B17]">{batch.item} <span className="ml-1 font-mono text-[10px] font-bold text-[#947870]">#{batch.batch}</span></p><p className="mt-1 text-xs font-medium text-[#80665D]">รับเข้า {batch.receiveDate} · เหลือ {batch.qty}</p></div><div className="sm:text-right"><p className="text-xs font-bold text-[#563D35]">EXP {batch.expireDate}</p><span className={`mt-1 inline-flex rounded-full border-2 border-[#2D1B17] px-2 py-0.5 text-[9px] font-black ${batch.status === 'Expiring Soon' ? 'bg-[#E7C7B8]' : 'bg-[#E8D8CA]'}`}>{batch.status === 'Expiring Soon' ? 'USE ME FIRST' : 'GOOD TO GO'}</span></div></div>)}</div><button onClick={() => navigate('/staff/freezer-stock')} className="w-full border-t-2 border-[#2D1B17] bg-[#2D1B17] px-6 py-3.5 text-xs font-black text-white transition hover:bg-[#513129]">เปิดคลังทั้งหมด →</button></div>
      <div className="space-y-6"><article className="rounded-[24px] border-2 border-[#2D1B17] bg-[#DBC8B8] p-6 shadow-[6px_6px_0_#2D1B17]"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Stock mix</h2><span className="text-xl">◒</span></div><p className="mt-1 text-xs font-semibold text-[#6F554D]">ล็อตพร้อมใช้แยกตามหมวด</p><div className="mt-5 space-y-4">{categoryCount.map(({ category, count }, index) => { const label = { Meat: 'เนื้อสัตว์', Vegetable: 'ผัก', Others: 'วัตถุดิบอื่น' }[category]; const colors = ['bg-[#B97861]', 'bg-[#CFAE91]', 'bg-[#E8D8CA]']; return <div key={category}><div className="mb-1.5 flex justify-between text-xs font-black"><span>{label}</span><span>{count} LOTS</span></div><div className="h-3 overflow-hidden rounded-full border-2 border-[#2D1B17] bg-white"><div className={`h-full ${colors[index]}`} style={{ width: `${usable.length ? Math.max(12, count / usable.length * 100) : 0}%` }}/></div></div>; })}</div></article><article className="relative rotate-[1deg] rounded-[24px] border-2 border-[#2D1B17] bg-[#E7C7B8] p-6 shadow-[6px_6px_0_#2D1B17]"><span className="absolute -top-3 right-5 rounded-full border-2 border-[#2D1B17] bg-[#2D1B17] px-3 py-1 text-[9px] font-black text-white">TO-DO</span><h2 className="text-lg font-black">ก่อนเปิดรอบ ✦</h2><div className="mt-4 space-y-2"><p className="rounded-xl border-2 border-[#2D1B17] bg-white px-3 py-2.5 text-xs font-bold"><b className="text-[#8C4C39]">{expiring.length}</b> ล็อต ต้องหยิบใช้ก่อน</p><p className="rounded-xl border-2 border-[#2D1B17] bg-white px-3 py-2.5 text-xs font-bold"><b className="text-[#8C4C39]">{expired.length}</b> ล็อต ต้องแยกออก</p></div></article></div>
    </section>
  </div>;
}

function PopMetric({ label, value, detail, color, symbol }: { label: string; value: number; detail: string; color: string; symbol: string }) { return <article className={`group relative overflow-hidden rounded-[22px] border-2 border-[#2D1B17] p-5 shadow-[5px_5px_0_#2D1B17] transition hover:-translate-y-1 ${color}`}><span className="absolute right-4 top-3 text-3xl font-black opacity-20">{symbol}</span><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#6D5148]">{label}</p><p className="mt-2 text-4xl font-black tracking-tight text-[#2D1B17]">{String(value).padStart(2, '0')}</p><p className="mt-1 text-xs font-bold text-[#745B52]">{detail}</p></article>; }
